# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edbc79517d206d3280cd7b24d0352883565b4665f0eba887f9906dccd1a1c86eaebd74c3b8393ebcf9aa1c07d23a2fa4586edeb5df10c0d665d1cc0a8dbde14f

test:
  secret_key_base: f535599b3205d391618706e58d578d457e04b2dc403a145c596cf7d8556b3bb9d7e7001bb80889cc9a52bc8cafb6473a97c27248afae89ec694e9ae5d44a414e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
